version: 0.2
phases:
  pre_build:
    commands:
      - echo `aws --version`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Moving build to website
      - aws s3 cp ./dist $S3_BUCKET --recursive